logging:
  level:
    org.springframework.web: WARN
    com.ote.test: INFO

server:
  port: ${PORT:7070}

spring:
  application:
    name: ApiGateway

zuul:
  routes:
    test-service:
      url: "DYNAMIC|http://localhost:8080"
      sensitiveHeaders:
    user-service:
      url: "http://localhost:8079"
      sensitiveHeaders:
    routing-configuration-service:
      url: "http://localhost:8078"
      sensitiveHeaders:

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000